# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-06-10 01:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0003_auto_20180610_0907'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usermessage',
            old_name='massage',
            new_name='message',
        ),
    ]
